### ISSUE TITLE
[refactor] 닉네임에 특수문자가 포함될 수 없도록 한다.

### ISSUE THREAD

**Issue by kpeel5839** [ConceptBe/conceptbe-backend#77]
### 🔨 Describe

현재 기획상 닉네임에 특수문자가 포함되면 안되는 것 같아요!
그래서, 이 부분은 수정해야 할 것 킹습니다.

### ✅ Tasks

- [x] 닉네임을 VO 로 감싼다.
- [x] VO 내부에 validation 로직을 구성한다.
- [x] 이에 대한 테스트 코드를 작성한다.
